name: aats
channels:
  - plotly
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - dash==2.14.2
  - plotly==5.18.0
  - dash-bootstrap-components==1.5.0
  - dash-mantine-components==0.12.1
  - gunicorn>=20.0.4
  - netcdf4>=1.5.8
  - numpy>=1.23.5,<2
  - pandas>=1.5.3,<2
  - werkzeug>=2.1.1
  - xarray>=2022.3.0
  - folium>=0.12.1
  - tqdm>=4.64.0
  - toolz>=0.11.2
  - diskcache>=5.4.0
  - numba>=0.53.1
  - pyproj>=3.5.0
  - scipy>=1.9.3
  - dacite==1.8.1
  - pip:
    - icoscp>=0.2.0