name: aa-time-series-env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - requests
  - numpy
  - pandas
  - xarray
  - plotly>=5.4
  - dash>=2.0
  - jupyter-dash
  - folium
  - ipykernel==5.5.5
  - IPython==7.26.0
  - notebook==6.0.3
  - pip:
    - icoscp
